services:
  api:
    build: .\api
    container_name: api
    ports:
      - "8000:8000"
    environment:
      API_HTTP_ADDRESS: 0.0.0.0:8000
      API_GRPC_ADDRESS: 0.0.0.0:50052
      DB_HOST: db_marketplace
      DB_PORT: 5432
      DB_USER: misha
      DB_PASSWORD: 1111
      DB_NAME: marketplace
    depends_on:
      migrate_api:
        condition: service_completed_successfully
  partner_api:
    build: .\partner_api
    container_name: partner_api
    ports:
      - "8001:8001"
    environment:
      PARTNER_API_HTTP_ADDRESS: 0.0.0.0:8001
      API_GRPC_ADDRESS: api:50052
      DB_HOST: db_partners
      DB_PORT: 5432
      DB_USER: misha
      DB_PASSWORD: 1111
      DB_NAME: partners
    depends_on:
      migrate_partner:
        condition: service_completed_successfully
      api:
        condition: service_started

  db_marketplace:
    image: postgres:latest
    container_name: db_marketplace
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: misha
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: marketplace
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U misha -d marketplace"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_partners:
    image: postgres:latest
    container_name: db_partners
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: misha
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: partners
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U misha -d partners"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate_api:
    image: flyway/flyway:latest
    volumes:
      - ./api/pgrepo/migrations:/flyway/sql
    command: -url=jdbc:postgresql://db_marketplace:5432/marketplace -user=misha -password=1111 -connectRetries=60 migrate
    depends_on:
      db_marketplace:
        condition: service_healthy

  migrate_partner:
    image: flyway/flyway:latest
    volumes:
      - ./partner_api/pgrepo/migrations:/flyway/sql
    command: -url=jdbc:postgresql://db_partners:5432/partners -user=misha -password=1111 -connectRetries=60 migrate
    depends_on:
      db_partners:
        condition: service_healthy
