// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: definitions/marketplace_api.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_definitions_marketplace_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_definitions_marketplace_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_definitions_marketplace_api_proto_rawDescGZIP(), []int{0}
}

type ProductId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductId) Reset() {
	*x = ProductId{}
	mi := &file_definitions_marketplace_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductId) ProtoMessage() {}

func (x *ProductId) ProtoReflect() protoreflect.Message {
	mi := &file_definitions_marketplace_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductId.ProtoReflect.Descriptor instead.
func (*ProductId) Descriptor() ([]byte, []int) {
	return file_definitions_marketplace_api_proto_rawDescGZIP(), []int{1}
}

func (x *ProductId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProductToAdd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductToAdd) Reset() {
	*x = ProductToAdd{}
	mi := &file_definitions_marketplace_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductToAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductToAdd) ProtoMessage() {}

func (x *ProductToAdd) ProtoReflect() protoreflect.Message {
	mi := &file_definitions_marketplace_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductToAdd.ProtoReflect.Descriptor instead.
func (*ProductToAdd) Descriptor() ([]byte, []int) {
	return file_definitions_marketplace_api_proto_rawDescGZIP(), []int{2}
}

func (x *ProductToAdd) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductToAdd) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ProductToRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	LeftInStock   int32                  `protobuf:"varint,3,opt,name=left_in_stock,json=leftInStock,proto3" json:"left_in_stock,omitempty"`
	ProviderId    int32                  `protobuf:"varint,4,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductToRegister) Reset() {
	*x = ProductToRegister{}
	mi := &file_definitions_marketplace_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductToRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductToRegister) ProtoMessage() {}

func (x *ProductToRegister) ProtoReflect() protoreflect.Message {
	mi := &file_definitions_marketplace_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductToRegister.ProtoReflect.Descriptor instead.
func (*ProductToRegister) Descriptor() ([]byte, []int) {
	return file_definitions_marketplace_api_proto_rawDescGZIP(), []int{3}
}

func (x *ProductToRegister) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductToRegister) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ProductToRegister) GetLeftInStock() int32 {
	if x != nil {
		return x.LeftInStock
	}
	return 0
}

func (x *ProductToRegister) GetProviderId() int32 {
	if x != nil {
		return x.ProviderId
	}
	return 0
}

func (x *ProductToRegister) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type AddProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductToAdd        `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductsRequest) Reset() {
	*x = AddProductsRequest{}
	mi := &file_definitions_marketplace_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsRequest) ProtoMessage() {}

func (x *AddProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_definitions_marketplace_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsRequest.ProtoReflect.Descriptor instead.
func (*AddProductsRequest) Descriptor() ([]byte, []int) {
	return file_definitions_marketplace_api_proto_rawDescGZIP(), []int{4}
}

func (x *AddProductsRequest) GetProducts() []*ProductToAdd {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_definitions_marketplace_api_proto protoreflect.FileDescriptor

const file_definitions_marketplace_api_proto_rawDesc = "" +
	"\n" +
	"!definitions/marketplace_api.proto\x12\finternalgrpc\"\a\n" +
	"\x05Empty\"\x1b\n" +
	"\tProductId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"6\n" +
	"\fProductToAdd\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"\x9e\x01\n" +
	"\x11ProductToRegister\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\"\n" +
	"\rleft_in_stock\x18\x03 \x01(\x05R\vleftInStock\x12\x1f\n" +
	"\vprovider_id\x18\x04 \x01(\x05R\n" +
	"providerId\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"L\n" +
	"\x12AddProductsRequest\x126\n" +
	"\bproducts\x18\x01 \x03(\v2\x1a.internalgrpc.ProductToAddR\bproducts2\xb6\x01\n" +
	"\x13MarketplaceInternal\x12M\n" +
	"\x12AddProductsInStock\x12 .internalgrpc.AddProductsRequest\x1a\x13.internalgrpc.Empty\"\x00\x12P\n" +
	"\x12RegisterNewProduct\x12\x1f.internalgrpc.ProductToRegister\x1a\x17.internalgrpc.ProductId\"\x00B\x17Z\x15definitions/generatedb\x06proto3"

var (
	file_definitions_marketplace_api_proto_rawDescOnce sync.Once
	file_definitions_marketplace_api_proto_rawDescData []byte
)

func file_definitions_marketplace_api_proto_rawDescGZIP() []byte {
	file_definitions_marketplace_api_proto_rawDescOnce.Do(func() {
		file_definitions_marketplace_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_definitions_marketplace_api_proto_rawDesc), len(file_definitions_marketplace_api_proto_rawDesc)))
	})
	return file_definitions_marketplace_api_proto_rawDescData
}

var file_definitions_marketplace_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_definitions_marketplace_api_proto_goTypes = []any{
	(*Empty)(nil),              // 0: internalgrpc.Empty
	(*ProductId)(nil),          // 1: internalgrpc.ProductId
	(*ProductToAdd)(nil),       // 2: internalgrpc.ProductToAdd
	(*ProductToRegister)(nil),  // 3: internalgrpc.ProductToRegister
	(*AddProductsRequest)(nil), // 4: internalgrpc.AddProductsRequest
}
var file_definitions_marketplace_api_proto_depIdxs = []int32{
	2, // 0: internalgrpc.AddProductsRequest.products:type_name -> internalgrpc.ProductToAdd
	4, // 1: internalgrpc.MarketplaceInternal.AddProductsInStock:input_type -> internalgrpc.AddProductsRequest
	3, // 2: internalgrpc.MarketplaceInternal.RegisterNewProduct:input_type -> internalgrpc.ProductToRegister
	0, // 3: internalgrpc.MarketplaceInternal.AddProductsInStock:output_type -> internalgrpc.Empty
	1, // 4: internalgrpc.MarketplaceInternal.RegisterNewProduct:output_type -> internalgrpc.ProductId
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_definitions_marketplace_api_proto_init() }
func file_definitions_marketplace_api_proto_init() {
	if File_definitions_marketplace_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_definitions_marketplace_api_proto_rawDesc), len(file_definitions_marketplace_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_definitions_marketplace_api_proto_goTypes,
		DependencyIndexes: file_definitions_marketplace_api_proto_depIdxs,
		MessageInfos:      file_definitions_marketplace_api_proto_msgTypes,
	}.Build()
	File_definitions_marketplace_api_proto = out.File
	file_definitions_marketplace_api_proto_goTypes = nil
	file_definitions_marketplace_api_proto_depIdxs = nil
}
